insert into category(description) values ('American');
insert into category(description) values ('Italian');
insert into category(description) values ('Mexican');
insert into category(description) values ('Fast Food');
insert into unit_of_measure(uom) values ('Teaspoon');
insert into unit_of_measure(uom) values ('Tablespoon');
insert into unit_of_measure(uom) values ('Cup');
insert into unit_of_measure(uom) values ('Pinch');
insert into unit_of_measure(uom) values ('Ripe');
insert into unit_of_measure(uom) values ('Tbsp');
insert into unit_of_measure(uom) values ('Serrano');
insert into unit_of_measure(uom) values ('Dash');
insert into unit_of_measure(uom) values ('Clove');
insert into unit_of_measure(uom) values ('Pint');
insert into unit_of_measure(uom) values ('Each');
